// frontend/src/App.tsx
import { useEffect, useCallback } from 'react';
import { BrowserRouter, Routes, Route, useNavigate } from 'react-router-dom';
import {
  NotificationProvider,
  ThemeProvider,
  CartProvider,
  WishlistProvider,
} from './contexts';
import { Header, Footer, CartSidebar, NotificationToast } from './components/shared';
import { HomePage } from './components/features/home';
import { WishlistPage } from './components/features/wishlist';

function AppContent() {
  const navigate = useNavigate();

  const handleFilterCategory = useCallback(
    (category: string) => {
      const queryParams = category === 'all' ? '' : `?category=${category}`;
      navigate(`/${queryParams}`);
    },
    [navigate]
  );

  useEffect(() => {
    // Preload all products when app starts
    import('./services').then(({ getProducts }) => {
      getProducts();
    });
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-gray-50 font-sans">
      <Header onFilterCategory={handleFilterCategory} />

      <div className="flex-1">
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/wishlist" element={<WishlistPage />} />
          <Route path="*" element={<HomePage />} />
        </Routes>
      </div>

      <Footer />

      <CartSidebar />
      <NotificationToast />
    </div>
  );
}

function App() {
  return (
    <BrowserRouter>
      <ThemeProvider>
        <NotificationProvider>
          <CartProvider>
            <WishlistProvider>
              <AppContent />
            </WishlistProvider>
          </CartProvider>
        </NotificationProvider>
      </ThemeProvider>
    </BrowserRouter>
  );
}

export default App;

// frontend/src/app/app.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './shared/components/header/header.component';
import { FooterComponent } from './shared/components/footer/footer.component';
import { CartSidebarComponent } from './shared/components/cart-sidebar/cart-sidebar.component';
import { NotificationToastComponent } from './shared/components/notification-toast/notification-toast.component';
import { ProductService } from './core/services/product.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    HeaderComponent,
    FooterComponent,
    CartSidebarComponent,
    NotificationToastComponent,
  ],
  template: `
    <div class="min-h-screen flex flex-col bg-gray-50 font-sans">
      <app-header (filterCategory)="onFilterCategory($event)"></app-header>

      <div class="flex-1">
        <router-outlet></router-outlet>
      </div>

      <app-footer></app-footer>
    </div>

    <app-cart-sidebar></app-cart-sidebar>
    <app-notification-toast></app-notification-toast>
  `,
})
export class AppComponent implements OnInit {
  private productService = inject(ProductService);
  private router = inject(Router);

  ngOnInit(): void {
    // Preload all products for cache
    this.productService.getAllProducts().subscribe();
  }

  onFilterCategory(category: string): void {
    const queryParams = category === 'all' ? {} : { category };
    this.router.navigate(['/'], { queryParams });
  }
}
