// frontend/src/components/shared/LoadingSpinner.tsx
interface LoadingSpinnerProps {
  message?: string;
}

export function LoadingSpinner({ message = 'Loading our collection...' }: LoadingSpinnerProps) {
  return (
    <div className="text-center py-12">
      <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-gold"></div>
      {message && <p className="mt-4 text-gray-600">{message}</p>}
    </div>
  );
}

// frontend/src/app/shared/components/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  template: `
    <div class="text-center py-12">
      <div class="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-gold"></div>
      @if (message) {
        <p class="mt-4 text-gray-600">{{ message }}</p>
      }
    </div>
  `
})
export class LoadingSpinnerComponent {
  @Input() message = 'Loading our collection...';
}
